"""Materialize skill runtime config from environment variables.

Some skills read a `config.env` that sits beside their SKILL.md rather than
reading the process environment directly - notably `wearhongxiu-wp`, whose
scripts do `SKILL_DIR / "config.env"`. That file holds live credentials, so it
is deliberately absent from version control and is rebuilt here at container
start from the Coolify environment. Nothing secret is baked into the image.

Run from the entrypoint before the server starts.
"""

from __future__ import annotations

import os
from pathlib import Path

SKILL_ROOT = Path(os.getenv("DSH_SKILL_ROOT", "/root/.codex/skills"))
WEAR_DIR = SKILL_ROOT / "wearhongxiu-wp"
WEAR_CONFIG = WEAR_DIR / "config.env"

# zoho-api reads ~/.zoho-api/.env (or config.json) rather than the environment,
# exactly as codex-worker's entrypoint arranges.
ZOHO_DIR = Path(os.getenv("ZOHO_CONFIG_DIR", str(Path.home() / ".zoho-api")))
ZOHO_ENV = ZOHO_DIR / ".env"

ZOHO_KEYS = [
    "ZOHO_REGION",
    "ZOHO_CLIENT_ID",
    "ZOHO_CLIENT_SECRET",
    "ZOHO_REFRESH_TOKEN",
    "ZOHO_CAMPAIGNS_LIST_NAME",
    "ZOHO_CAMPAIGNS_TOPIC_NAME",
    "ZOHO_CAMPAIGNS_FROM_EMAIL",
    "ZOHO_CAMPAIGNS_FROM_NAME",
]

# Written in this order, matching the skill's own config.example.env so the file
# stays familiar. Values come from the process environment.
WEAR_KEYS = [
    "WEARHONGXIU_WP_URL",
    "WEARHONGXIU_WP_USER",
    "WEARHONGXIU_WP_APP_PASSWORD",
    "WEARHONGXIU_WP_TIMEOUT",
    "WEARHONGXIU_HOSTINGER_API_TOKEN",
    "WEARHONGXIU_HOSTINGER_USERNAME",
    "WEARHONGXIU_HOSTINGER_DOMAIN",
    "WEARHONGXIU_HOSTINGER_API_BASE",
    "WEARHONGXIU_NEWSAPI_KEY",
    "WEARHONGXIU_JINA_API_TOKEN",
    "WEARHONGXIU_LLM_BASE_URL",
    "WEARHONGXIU_LLM_API_KEY",
    "WEARHONGXIU_LLM_MODEL",
    "WEARHONGXIU_VISION_LLM_BASE_URL",
    "WEARHONGXIU_VISION_LLM_API_KEY",
    "WEARHONGXIU_VISION_LLM_MODEL",
    "HONGXIU_RAG_TOKEN",
    "WEARHONGXIU_GSC_CREDENTIALS",
    "WEARHONGXIU_GSC_SITE_URL",
    "WEARHONGXIU_GSC_SITEMAP_URL",
    "WEARHONGXIU_GA4_CREDENTIALS",
    "WEARHONGXIU_PAGESPEED_API_KEY",
]


def write_secret_file(path: Path, header: str, values: dict[str, str]) -> None:
    """Write KEY=value lines at 0600, via a temp file so it is never world-readable."""
    path.parent.mkdir(parents=True, exist_ok=True)
    temporary = path.with_suffix(path.suffix + ".tmp")
    descriptor = os.open(temporary, os.O_WRONLY | os.O_CREAT | os.O_TRUNC, 0o600)
    with os.fdopen(descriptor, "w", encoding="utf-8") as handle:
        handle.write(header)
        for key, value in values.items():
            handle.write(f"{key}={value}\n")
    temporary.replace(path)
    os.chmod(path, 0o600)


def write_zoho() -> str:
    present = {key: os.environ.get(key, "") for key in ZOHO_KEYS}
    if not any(v.strip() for v in present.values()):
        return "skipped (no ZOHO_* variables are set)"
    required = ("ZOHO_REGION", "ZOHO_CLIENT_ID", "ZOHO_CLIENT_SECRET", "ZOHO_REFRESH_TOKEN")
    missing = [k for k in required if not present[k].strip()]
    if missing:
        return f"skipped (incomplete: {', '.join(missing)} missing)"
    write_secret_file(
        ZOHO_ENV,
        "# Generated by dsh-worker configure_skills.py from the Coolify\n"
        "# environment. Do not edit: it is rebuilt on every start.\n",
        present,
    )
    return f"wrote {ZOHO_ENV}"


def write_wearhongxiu() -> str:
    present = {key: os.environ.get(key, "") for key in WEAR_KEYS}
    if not any(value.strip() for value in present.values()):
        return "skipped (no WEARHONGXIU_* variables are set)"
    if not WEAR_DIR.is_dir():
        return f"skipped ({WEAR_DIR} is not present in this image)"

    # 0600 before any secret lands in the file, never after.
    write_secret_file(
        WEAR_CONFIG,
        "# Generated by dsh-worker configure_skills.py from the\n"
        "# Coolify environment. Do not edit: it is rebuilt on every start.\n",
        present,
    )
    configured = sum(1 for v in present.values() if v.strip())
    return f"wrote {WEAR_CONFIG} with {configured}/{len(WEAR_KEYS)} values set"


def main() -> None:
    print("configure_skills:", write_zoho())
    print("configure_skills:", write_wearhongxiu())


if __name__ == "__main__":
    main()
