#!/usr/bin/env python3
"""Inspect and correct an unreasonable Wearhongxiu product variant label.

The colour label on a Wearhongxiu product is generated by the 1688 collector
from the captured source SKU options, so a bare merchant code such as `9007`
reaches the storefront, and editing WordPress alone is not durable: the next
capture, translation refresh, or swatch repair writes the code back.

This command owns both halves of the fix:

1. it records a manual display-name override on the collector product, which is
   what makes the corrected name survive later captures and repairs; and
2. it writes the corrected labels into the live WordPress product through the
   authenticated `hx/v1` product sync, without re-uploading any media.

Nothing is written without `--apply`. Read references/variant-rename.md before
using it.
"""

from __future__ import annotations

import argparse
import copy
import json
import os
import re
import subprocess
import sys
import urllib.error
import urllib.parse
import urllib.request
from pathlib import Path
from urllib.parse import urlparse

from wp import ApiError, Client, config

try:  # Present on the worker images, absent in a plain local checkout.
    from skill_credentials import load as _load_skill_credentials
except ImportError:  # pragma: no cover - depends on the runtime layout
    _load_skill_credentials = None

SKILL_DIR = Path(__file__).resolve().parent.parent

# The collector application whose environment holds the collector bearer key.
COLLECTOR_APP_UUID = "kc1izz5i6mnhs9z29ckl1ajp"
COLLECTOR_DEFAULT_URL = "https://collector.yiswim.cloud"
COLLECTOR_ALLOWED_SUFFIX = ".yiswim.cloud"
# This skill's own names first, then the names the collector skill and the
# worker credential file use.
COLLECTOR_URL_KEYS = ("HONGXIU_COLLECTOR_API_URL", "COLLECTOR_API_URL")
COLLECTOR_KEY_KEYS = ("HONGXIU_COLLECTOR_API_KEY", "COLLECTOR_API_KEY")
COLOR_KEYS = ("color", "颜色")
MAX_LABEL = 120
# Cloudflare in front of the collector blocks the default urllib signature, so
# send the same browser-compatible headers the skill's other API clients use.
USER_AGENT = ("Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 "
              "(KHTML, like Gecko) Chrome/153.0.0.0 Safari/537.36")


def die(message: str) -> None:
    print(f"ERROR: {message}", file=sys.stderr)
    raise SystemExit(1)


def load_env(path: Path) -> dict[str, str]:
    values: dict[str, str] = {}
    try:
        for raw in path.read_text(encoding="utf-8").splitlines():
            line = raw.strip()
            if not line or line.startswith("#") or "=" not in line:
                continue
            key, value = line.split("=", 1)
            values[key.strip()] = value.strip().strip('"').strip("'")
    except FileNotFoundError:
        pass
    return values


def normalize_text(value) -> str:
    return re.sub(r"\s+", " ", str(value or "")).strip().lower()


def clean_label(value) -> str:
    return re.sub(r"\s+", " ", str(value or "")).strip()


# --------------------------------------------------------------------------- #
# Collector access
# --------------------------------------------------------------------------- #


def coolify_env_value(key: str) -> str:
    """Read one collector environment value from Coolify without printing it."""
    path = Path.home() / ".coolify" / "config.json"
    if not path.exists():
        return ""
    cfg = json.loads(path.read_text(encoding="utf-8"))
    url = f"{cfg['base_url']}/applications/{COLLECTOR_APP_UUID}/envs"
    request = urllib.request.Request(
        url, headers={"Authorization": f"Bearer {cfg['token']}", "Accept": "application/json"}
    )
    for entry in json.load(urllib.request.urlopen(request, timeout=60)):
        if entry.get("key") == key and str(entry.get("value", "")).strip():
            return str(entry["value"]).strip()
    return ""


def collector_config() -> tuple[str, str]:
    # The harness scrubs KEY/TOKEN-shaped variables from shell commands, so on a
    # worker image the values come from the skill credential file instead.
    if _load_skill_credentials:
        _load_skill_credentials(*COLLECTOR_URL_KEYS, *COLLECTOR_KEY_KEYS)

    def first(keys) -> str:
        for key in keys:
            value = os.environ.get(key, "").strip()
            if value:
                return value
        return ""

    base = first(COLLECTOR_URL_KEYS)
    key = first(COLLECTOR_KEY_KEYS)
    if not (base and key):
        cfg = load_env(SKILL_DIR / "config.env")
        base = base or cfg.get("HONGXIU_COLLECTOR_API_URL", "").strip()
        key = key or cfg.get("HONGXIU_COLLECTOR_API_KEY", "").strip()
    if not base:
        base = COLLECTOR_DEFAULT_URL
    host = (urlparse(base).hostname or "").lower()
    if not host.endswith(COLLECTOR_ALLOWED_SUFFIX):
        die(f"Refusing to send the collector key to {host or base!r}")
    if not key:
        key = coolify_env_value("ADMIN_API_KEY")
    if not key:
        die("No collector key. Set HONGXIU_COLLECTOR_API_KEY or configure the collector app.")
    return base.rstrip("/"), key


class Collector:
    def __init__(self) -> None:
        self.base, self.key = collector_config()

    def request(self, method: str, path: str, body=None, timeout: int = 300):
        data = json.dumps(body).encode("utf-8") if body is not None else None
        request = urllib.request.Request(
            f"{self.base}{path}",
            data=data,
            method=method,
            headers={
                "Authorization": f"Bearer {self.key}",
                "Accept": "application/json",
                "Content-Type": "application/json",
                "User-Agent": USER_AGENT,
            },
        )
        try:
            with urllib.request.urlopen(request, timeout=timeout) as response:
                raw = response.read().decode("utf-8", "replace")
                return json.loads(raw) if raw else None
        except urllib.error.HTTPError as error:
            detail = error.read().decode("utf-8", "replace")
            try:
                detail = json.loads(detail)
            except ValueError:
                detail = detail[:400]
            die(f"collector {method} {path} -> HTTP {error.code}: {detail}")
        except urllib.error.URLError as error:
            die(f"cannot reach the collector at {self.base}: {error.reason}")


# --------------------------------------------------------------------------- #
# Product resolution
# --------------------------------------------------------------------------- #


def resolver_params(identifier: str) -> dict[str, str]:
    if identifier.isdigit():
        return {"post_id": identifier}
    if identifier.startswith("https://"):
        host = (urlparse(identifier).hostname or "").lower()
        if host not in {"wearhongxiu.com", "www.wearhongxiu.com"}:
            die(f"Off-site product URL is not allowed: {identifier}")
        return {"url": identifier}
    if re.fullmatch(r"[A-Za-z0-9_-]{2,40}", identifier):
        return {"style_no": identifier}
    return {"slug": identifier}


def resolve_wordpress(client: Client, identifier: str) -> dict:
    params = resolver_params(identifier)
    try:
        resolved, _ = client.request("GET", "/hx/v1/products/resolve", params=params)
    except ApiError:
        if "style_no" not in params:
            raise
        resolved, _ = client.request("GET", "/hx/v1/products/resolve", params={"slug": identifier})
    return resolved


def collector_product(collector: Collector, style_no: str) -> dict:
    if not style_no:
        die("The WordPress product has no style number, so the collector source cannot be resolved.")
    resolved = collector.request(
        "GET", f"/api/wordpress/products/resolve?{urllib.parse.urlencode({'styleNo': style_no})}"
    )
    entry = (resolved or {}).get("collector") or {}
    if not entry.get("product_detail_id"):
        die(
            f"{style_no} has no collector source, so an override cannot be stored. "
            "This product is not collector-managed."
        )
    return entry


def captured_color_texts(collector: Collector, detail_id) -> list[str]:
    detail = collector.request("GET", f"/api/product-details/{detail_id}") or {}
    values: list[str] = []
    for sku in detail.get("skus") or []:
        for key, value in (sku.get("option_data") or {}).items():
            if normalize_text(key) in COLOR_KEYS and clean_label(value):
                if clean_label(value) not in values:
                    values.append(clean_label(value))
    return values


# --------------------------------------------------------------------------- #
# Label mapping, mirroring the collector's own override rules
# --------------------------------------------------------------------------- #


def swatch_source_text(color: dict) -> str:
    return clean_label(color.get("source_label") or color.get("label"))


def preview_sources(preview: dict) -> dict[str, list[str]]:
    """Colour value -> every text that identifies that colour.

    A colour can be named by its corrected label, by the translated option the
    collector publishes, or by the raw captured 1688 text, and the operator may
    use any of them. The SKU matrix is what links a published label to its
    captured source text.
    """
    raw_by_display: dict[str, set[str]] = {}
    for row in (preview.get("sku_matrix") or {}).get("rows") or []:
        raw = [clean_label(value) for key, value in (row.get("source_options") or {}).items()
               if normalize_text(key) in COLOR_KEYS]
        displays = [clean_label(row.get("color"))]
        displays += [clean_label(value) for key, value in (row.get("options") or {}).items()
                     if normalize_text(key) in COLOR_KEYS]
        for display in displays:
            if display:
                raw_by_display.setdefault(normalize_text(display), set()).update(filter(None, raw))

    sources: dict[str, list[str]] = {}
    for color in (preview.get("colors") or {}).get("colors") or []:
        identifiers = {swatch_source_text(color), clean_label(color.get("label"))}
        identifiers = {value for value in identifiers if value}
        captured: set[str] = set()
        for identifier in identifiers:
            captured |= raw_by_display.get(normalize_text(identifier), set())
        sources[str(color.get("value"))] = sorted(identifiers | captured)
    return sources


def matching_keys(sources: dict[str, list[str]] | None, value: str, color: dict) -> set[str]:
    keys = {normalize_text(swatch_source_text(color)), normalize_text(color.get("label"))}
    keys |= {normalize_text(item) for item in (sources or {}).get(str(value)) or []}
    return {key for key in keys if key}


def rename_payload(payload: dict, source: str, target: str,
                   sources: dict[str, list[str]] | None = None) -> tuple[dict, list[str]]:
    """Return the synced payload plus the colour values that were renamed.

    Matching uses the explicit `source_label` provenance, the texts the
    collector associates with that colour, and the published label. That lets an
    already-corrected product be renamed again even though its storefront label
    no longer shows the captured code.
    """
    updated = copy.deepcopy(payload)
    key = normalize_text(source)
    renamed: list[str] = []

    for color in (updated.get("colors") or {}).get("colors") or []:
        value = str(color.get("value"))
        if key not in matching_keys(sources, value, color):
            continue
        color["source_label"] = clean_label(color.get("source_label") or source)
        color["label"] = target
        renamed.append(value)

    for row in (updated.get("sku_matrix") or {}).get("rows") or []:
        options = row.get("options") or {}
        source_options = row.get("source_options") or {}
        values = [row.get("color"),
                  *[v for k, v in options.items() if normalize_text(k) in COLOR_KEYS],
                  *[v for k, v in source_options.items() if normalize_text(k) in COLOR_KEYS]]
        if not any(normalize_text(value) == key for value in values):
            continue
        for option_key in list(options):
            if normalize_text(option_key) in COLOR_KEYS:
                options[option_key] = target
        if normalize_text(row.get("color")) == key:
            row["color"] = target

    return updated, renamed


def payload_for_sync(resolved: dict, labels: dict | None = None) -> dict:
    """Build the exact payload the `hx/v1/products/sync` route requires.

    That route rewrites title, description, status, and every meta key it is
    given, so the resolver snapshot is replayed in full; categories, tags, and
    images are omitted so the live terms, gallery, and featured image stay
    untouched.
    """
    meta = dict(resolved.get("meta") or {})
    payload = {
        "external_id": resolved.get("external_id"),
        "style_no": resolved.get("sku"),
        "title": resolved.get("title"),
        "description": meta.get("description", ""),
        "status": resolved.get("status") or "publish",
        "meta": meta,
        "colors": resolved.get("catalog", {}).get("colors"),
        "sku_matrix": resolved.get("catalog", {}).get("sku_matrix"),
    }
    for color in (payload.get("colors") or {}).get("colors") or []:
        target = (labels or {}).get(str(color.get("value")))
        if target and target != color.get("label"):
            color["source_label"] = clean_label(color.get("source_label") or color.get("label"))
            color["label"] = target
    return payload


def preview_payload(collector: Collector, detail_id, resolved: dict) -> dict:
    """Ask the collector what it would publish now, without a model call."""
    meta = resolved.get("meta") or {}
    categories = [c.get("id") for c in resolved.get("categories") or [] if c.get("id")]
    tags = [t.get("name") for t in resolved.get("tags") or [] if t.get("name")]
    primary = meta.get("primary_category_id") or (categories[0] if categories else None)
    body = {
        "status": resolved.get("status") or "publish",
        "styleNo": resolved.get("sku"),
        "categoryIds": categories,
        "primaryCategoryId": int(primary) if str(primary or "").isdigit() else None,
        "categoryMode": "manual",
        "tagMode": "manual",
        "tags": tags,
        "material": meta.get("material") or "Polyester",
    }
    body = {key: value for key, value in body.items() if value not in (None, [], "")}
    result = collector.request("POST", f"/api/product-details/{detail_id}/wordpress/preview", body)
    return (result or {}).get("payload") or {}


def assert_preview_matches(preview: dict, payload: dict) -> None:
    expected = {str(c.get("value")): clean_label(c.get("label"))
                for c in (payload.get("colors") or {}).get("colors") or []}
    actual = {str(c.get("value")): clean_label(c.get("label"))
              for c in (preview.get("colors") or {}).get("colors") or []}
    if expected != actual:
        die(f"The collector would publish {actual} but WordPress was set to {expected}.")
    expected_rows = {r.get("source_sku_key"): clean_label(r.get("color"))
                     for r in (payload.get("sku_matrix") or {}).get("rows") or []}
    actual_rows = {r.get("source_sku_key"): clean_label(r.get("color"))
                   for r in (preview.get("sku_matrix") or {}).get("rows") or []}
    if expected_rows != actual_rows:
        die(f"The collector SKU matrix disagrees with WordPress: {actual_rows} vs {expected_rows}.")


# --------------------------------------------------------------------------- #
# Commands
# --------------------------------------------------------------------------- #


def state(client: Client, collector: Collector, identifier: str) -> dict:
    resolved = resolve_wordpress(client, identifier)
    source = collector_product(collector, resolved.get("sku"))
    detail_id = source.get("product_detail_id")
    colors = (resolved.get("catalog") or {}).get("colors", {}).get("colors") or []
    overrides = (collector.request("GET", f"/api/product-details/{detail_id}/option-overrides")
                 or {}).get("overrides") or []
    # What the collector currently matches each colour on, before any new rename.
    current = preview_payload(collector, detail_id, resolved)
    return {
        "resolved": resolved,
        "collector": source,
        "detail_id": detail_id,
        "colors": colors,
        "captured": captured_color_texts(collector, detail_id),
        "overrides": overrides,
        "sources": preview_sources(current),
    }


def report(snapshot: dict) -> None:
    resolved = snapshot["resolved"]
    print(f"Product : {resolved.get('title')}")
    print(f"URL     : {resolved.get('permalink')}")
    print(f"Style   : {resolved.get('sku')}   post {resolved.get('post_id')}   "
          f"collector detail {snapshot['detail_id']}")
    print(f"Captured source colour text : {', '.join(snapshot['captured']) or '(none)'}")
    print("Published variants:")
    for color in snapshot["colors"]:
        value = str(color.get("value"))
        names = snapshot["sources"].get(value) or [swatch_source_text(color)]
        print(f"  - {value:8} label={color.get('label')!r}"
              f"  matched_on={', '.join(repr(name) for name in names)}"
              f"  image_id={color.get('image_id')}")
    if snapshot["overrides"]:
        print("Stored overrides:")
        for row in snapshot["overrides"]:
            print(f"  - id={row.get('id')} {row.get('dimension_name')} "
                  f"{row.get('source_text')!r} -> {row.get('display_label')!r}")
    else:
        print("Stored overrides: (none)")


def require_match(snapshot: dict, source: str) -> None:
    known = {normalize_text(value) for value in snapshot["captured"]}
    known |= {normalize_text(swatch_source_text(color)) for color in snapshot["colors"]}
    if normalize_text(source) not in known:
        die(f"{source!r} is not a colour on this product. Known values: "
            f"{sorted(value for value in known if value)}")


def command_inspect(client: Client, collector: Collector, args) -> int:
    report(state(client, collector, args.identifier))
    return 0


def command_apply(client: Client, collector: Collector, args) -> int:
    target = clean_label(args.label)
    if not target or len(target) > MAX_LABEL:
        die(f"--label must be 1 to {MAX_LABEL} characters")
    snapshot = state(client, collector, args.identifier)
    require_match(snapshot, args.source)
    payload, renamed = rename_payload(payload_for_sync(snapshot["resolved"]),
                                      args.source, target, snapshot["sources"])
    if not renamed:
        die(f"No published colour matches {args.source!r}.")
    print(f"Product : {snapshot['resolved'].get('title')}  ({snapshot['resolved'].get('sku')})")
    print(f"Rename  : {args.source!r} -> {target!r}  (colour values {', '.join(renamed)})")
    for color in snapshot["colors"]:
        if str(color.get("value")) in renamed:
            print(f"  - {color.get('value')}: {color.get('label')!r} -> {target!r}")
    if not args.apply:
        print("DRY RUN - nothing written. Re-run with --apply.")
        return 0

    saved = collector.request(
        "POST",
        f"/api/product-details/{snapshot['detail_id']}/option-overrides",
        {"sourceText": args.source, "displayLabel": target,
         "dimensionName": args.dimension, "note": args.note or ""},
    )
    print(f"Collector override saved: id={((saved or {}).get('override') or {}).get('id')}")

    client.request("POST", "/hx/v1/products/sync", data=payload)

    refreshed = resolve_wordpress(client, str(snapshot["resolved"].get("post_id")))
    labels = {str(c.get("value")): c.get("label")
              for c in (refreshed.get("catalog") or {}).get("colors", {}).get("colors") or []}
    print(f"WordPress now: {json.dumps(labels, ensure_ascii=False)}")

    if not args.no_verify:
        preview = preview_payload(collector, snapshot["detail_id"], refreshed)
        assert_preview_matches(preview, payload)
        print("Collector preview agrees with WordPress; later captures cannot revert this.")

    if args.purge_cache:
        subprocess.run([sys.executable, str(SKILL_DIR / "scripts" / "hostinger.py"),
                        "cache-purge"], check=False)
    return 0


def command_revert(client: Client, collector: Collector, args) -> int:
    snapshot = state(client, collector, args.identifier)
    matches = [row for row in snapshot["overrides"]
               if normalize_text(row.get("source_text")) == normalize_text(args.source)]
    if not matches:
        die(f"No stored override for {args.source!r}.")
    print("Overrides to remove:")
    for row in matches:
        print(f"  - id={row.get('id')} {row.get('source_text')!r} -> {row.get('display_label')!r}")
    if not args.apply:
        print("DRY RUN - nothing written. Re-run with --apply.")
        return 0

    for row in matches:
        collector.request(
            "DELETE",
            f"/api/product-details/{snapshot['detail_id']}/option-overrides/{row.get('id')}",
        )

    # The collector is the source of truth for the restored label.
    preview = preview_payload(collector, snapshot["detail_id"], snapshot["resolved"])
    labels = {str(c.get("value")): clean_label(c.get("label"))
              for c in (preview.get("colors") or {}).get("colors") or []}
    client.request("POST", "/hx/v1/products/sync", data=payload_for_sync(snapshot["resolved"], labels))
    print(f"Reverted; WordPress now: {json.dumps(labels, ensure_ascii=False)}")
    if args.purge_cache:
        subprocess.run([sys.executable, str(SKILL_DIR / "scripts" / "hostinger.py"),
                        "cache-purge"], check=False)
    return 0


def parser() -> argparse.ArgumentParser:
    root = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    root.add_argument("--config", help="Wearhongxiu config.env path")
    sub = root.add_subparsers(dest="command", required=True)

    for name, help_text in (("inspect", "Show the published variant labels and their sources"),
                            ("apply", "Record the override and correct WordPress"),
                            ("revert", "Remove the override and restore the captured label")):
        node = sub.add_parser(name, help=help_text)
        node.add_argument("identifier",
                          help="Style number, WordPress product URL, slug, or post ID")
        if name in {"apply", "revert"}:
            node.add_argument("--source", required=True,
                              help="The captured colour text to match, for example 9007")
            node.add_argument("--apply", action="store_true", help="Write the change")
            node.add_argument("--purge-cache", action="store_true",
                              help="Purge the Wearhongxiu cache after the write")
        if name == "apply":
            node.add_argument("--label", required=True, help="The corrected display name")
            node.add_argument("--dimension", default="color", help="Default: color")
            node.add_argument("--note", help="Why this label was chosen")
            node.add_argument("--no-verify", action="store_true",
                              help="Skip the collector preview cross-check")
    return root


def main() -> int:
    args = parser().parse_args()
    client = Client(config(args.config))
    collector = Collector()
    if args.command == "inspect":
        return command_inspect(client, collector, args)
    if args.command == "apply":
        return command_apply(client, collector, args)
    return command_revert(client, collector, args)


if __name__ == "__main__":
    raise SystemExit(main())
