#!/usr/bin/env python3
"""
image_text_overlay.py - Overlay crisp, customizable text captions onto static meme images.

Part of Crun Meme Generator Skill.
Overlay text captions onto static image artwork generated by Crun image models,
bypassing AI image model text rendering limitations (misspellings, font distortions, garbled text).

Usage:
  python image_text_overlay.py <image_path> [--output <output_path>] [--text "caption"] [--text-position bottom] [--style stroke|banner]
"""

import argparse
import json
import os
import sys
from PIL import Image, ImageDraw, ImageFont


def find_cjk_font():
    """Find system CJK/TrueType font for crisp Chinese/English text overlay."""
    font_candidates = [
        # Windows fonts
        "C:\\Windows\\Fonts\\msyh.ttc",     # Microsoft YaHei
        "C:\\Windows\\Fonts\\msyh.ttf",
        "C:\\Windows\\Fonts\\simhei.ttf",   # SimHei
        "C:\\Windows\\Fonts\\simsun.ttc",   # SimSun
        "C:\\Windows\\Fonts\\arial.ttf",
        # macOS fonts
        "/System/Library/Fonts/PingFang.ttc",
        "/Library/Fonts/Arial Unicode.ttf",
        # Linux fonts
        "/usr/share/fonts/opentype/noto/NotoSansCJK-Regular.ttc",
        "/usr/share/fonts/truetype/wqy/wqy-zenhei.ttc",
        "/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf",
    ]
    for font_path in font_candidates:
        if os.path.isfile(font_path):
            return font_path
    return None


def wrap_text(text, font, draw, max_width):
    """Wrap text to fit within max_width."""
    lines = []
    # If text already contains explicit newlines, preserve them
    paragraphs = text.split('\n')
    
    for paragraph in paragraphs:
        if not paragraph.strip():
            lines.append('')
            continue
        
        words = paragraph.split(' ')
        # If single long word or CJK text without spaces
        if len(words) == 1:
            current_line = ""
            for char in paragraph:
                test_line = current_line + char
                if hasattr(draw, "textbbox"):
                    w = draw.textbbox((0, 0), test_line, font=font)[2]
                elif hasattr(font, "getsize"):
                    w = font.getsize(test_line)[0]
                else:
                    w = len(test_line) * (font.size // 2)
                
                if w <= max_width or not current_line:
                    current_line = test_line
                else:
                    lines.append(current_line)
                    current_line = char
            if current_line:
                lines.append(current_line)
        else:
            current_line = ""
            for word in words:
                test_line = (current_line + " " + word).strip()
                if hasattr(draw, "textbbox"):
                    w = draw.textbbox((0, 0), test_line, font=font)[2]
                elif hasattr(font, "getsize"):
                    w = font.getsize(test_line)[0]
                else:
                    w = len(test_line) * (font.size // 2)
                
                if w <= max_width or not current_line:
                    current_line = test_line
                else:
                    lines.append(current_line)
                    current_line = word
            if current_line:
                lines.append(current_line)

    return lines


def overlay_text_on_image(image_path, output_path=None, text="", position="bottom", style="stroke", font_size=None):
    """Draw caption overlay on static image."""
    if not os.path.exists(image_path):
        raise FileNotFoundError(f"Input image file not found: {image_path}")

    img = Image.open(image_path).convert("RGBA")
    w, h = img.size

    if not output_path:
        base, ext = os.path.splitext(image_path)
        output_path = f"{base}_meme.png"

    if not text:
        # Save as RGB/PNG without edit
        img.convert("RGB").save(output_path)
        return {
            "code": 0,
            "status": "success",
            "input_file": image_path,
            "output_file": output_path,
            "width": w,
            "height": h,
            "text_overlay": "",
            "message": "No text requested. Image copied/saved."
        }

    # Font setup
    font_path = find_cjk_font()
    target_font_size = font_size if font_size else max(24, int(h * 0.075))
    
    font = None
    if font_path:
        try:
            font = ImageFont.truetype(font_path, size=target_font_size)
        except Exception:
            font = None
    if font is None:
        try:
            font = ImageFont.load_default()
        except Exception:
            font = None

    draw = ImageDraw.Draw(img)
    max_text_w = int(w * 0.9)
    lines = wrap_text(text, font, draw, max_text_w)

    # Line height calculation
    if hasattr(draw, "textbbox"):
        sample_bbox = draw.textbbox((0, 0), "Ag月国", font=font)
        line_h = (sample_bbox[3] - sample_bbox[1]) + int(target_font_size * 0.25)
    else:
        line_h = int(target_font_size * 1.25)

    total_text_h = len(lines) * line_h

    if style == "banner":
        # Create a top or bottom semi-transparent white/black banner box
        banner_h = total_text_h + int(h * 0.05)
        overlay = Image.new("RGBA", img.size, (0, 0, 0, 0))
        overlay_draw = ImageDraw.Draw(overlay)
        
        if position == "top":
            box_coords = [0, 0, w, banner_h]
            text_start_y = (banner_h - total_text_h) // 2
        else: # bottom or center
            box_coords = [0, h - banner_h, w, h]
            text_start_y = h - banner_h + (banner_h - total_text_h) // 2
        
        # Semi-transparent dark banner background
        overlay_draw.rectangle(box_coords, fill=(0, 0, 0, 160))
        img = Image.alpha_composite(img, overlay)
        draw = ImageDraw.Draw(img)

        # Draw white text on banner
        current_y = text_start_y
        for line in lines:
            if hasattr(draw, "textbbox"):
                line_w = draw.textbbox((0, 0), line, font=font)[2]
            elif hasattr(font, "getsize"):
                line_w = font.getsize(line)[0]
            else:
                line_w = len(line) * (target_font_size // 2)
            
            line_x = (w - line_w) // 2
            draw.text((line_x, current_y), line, fill=(255, 255, 255, 255), font=font)
            current_y += line_h

    else:
        # "stroke" style (Classic Meme: white text with black outline)
        if position == "top":
            start_y = int(h * 0.05)
        elif position == "center":
            start_y = (h - total_text_h) // 2
        else: # bottom
            start_y = h - total_text_h - int(h * 0.06)

        stroke_w = max(2, target_font_size // 14)
        current_y = start_y

        for line in lines:
            if hasattr(draw, "textbbox"):
                line_w = draw.textbbox((0, 0), line, font=font)[2]
            elif hasattr(font, "getsize"):
                line_w = font.getsize(line)[0]
            else:
                line_w = len(line) * (target_font_size // 2)
            
            line_x = max(10, (w - line_w) // 2)
            
            try:
                # PIL stroke_fill feature
                draw.text(
                    (line_x, current_y),
                    line,
                    fill=(255, 255, 255, 255),
                    font=font,
                    stroke_width=stroke_w,
                    stroke_fill=(0, 0, 0, 255),
                )
            except Exception:
                # Manual outline fallback if stroke_width is unsupported
                for dx in range(-stroke_w, stroke_w + 1):
                    for dy in range(-stroke_w, stroke_w + 1):
                        if dx != 0 or dy != 0:
                            draw.text((line_x + dx, current_y + dy), line, fill=(0, 0, 0, 255), font=font)
                draw.text((line_x, current_y), line, fill=(255, 255, 255, 255), font=font)

            current_y += line_h

    # Convert to RGB and save PNG/JPG
    final_img = img.convert("RGB")
    final_img.save(output_path, quality=95)

    return {
        "code": 0,
        "status": "success",
        "input_file": image_path,
        "output_file": output_path,
        "width": w,
        "height": h,
        "text_overlay": text,
        "text_position": position,
        "style": style
    }


def main():
    parser = argparse.ArgumentParser(
        description="Overlay text caption onto static meme images (Crun Meme Generator)"
    )
    parser.add_argument("image_path", help="Path to input image file (PNG/JPG/WEBP)")
    parser.add_argument("--output", "-o", default=None, help="Output path for captioned meme image")
    parser.add_argument("--text", "-t", default="", help="Text caption string to overlay")
    parser.add_argument(
        "--text-position",
        choices=["bottom", "top", "center"],
        default="bottom",
        help="Position of text overlay (default: bottom)",
    )
    parser.add_argument(
        "--style",
        choices=["stroke", "banner"],
        default="stroke",
        help="Text overlay style: stroke (white with black border) or banner (dark box)",
    )
    parser.add_argument("--font-size", type=int, default=None, help="Font size in pixels (default: auto)")

    args = parser.parse_args()

    try:
        res = overlay_text_on_image(
            image_path=args.image_path,
            output_path=args.output,
            text=args.text,
            position=args.text_position,
            style=args.style,
            font_size=args.font_size,
        )
        print(json.dumps(res, ensure_ascii=False, indent=2))
        sys.exit(0)
    except Exception as e:
        err_res = {
            "code": 1,
            "status": "error",
            "error_message": str(e),
            "input_file": args.image_path,
        }
        print(json.dumps(err_res, ensure_ascii=False, indent=2))
        sys.exit(1)


if __name__ == "__main__":
    main()
