#!/usr/bin/env python3
"""
video_to_gif.py - Convert MP4/video files to animated GIF memes with optional text overlays.

Part of Crun Meme Generator Skill.
Converts a video generated by Crun video models into an optimized GIF meme file,
with optional direct text caption overlay (bypassing video AI model text generation).

Usage:
  python video_to_gif.py <video_path> [--output <gif_path>] [--fps <fps>] [--width <width>] [--text "caption"] [--text-position bottom]
"""

import argparse
import json
import os
import shutil
import subprocess
import sys
import tempfile


def find_ffmpeg():
    """Find ffmpeg binary in PATH or common system installation paths."""
    ffmpeg_bin = shutil.which("ffmpeg")
    if ffmpeg_bin:
        return ffmpeg_bin

    local_app_data = os.environ.get("LOCALAPPDATA", "")
    possible_paths = [
        os.path.join(local_app_data, "JianyingPro", "Apps"),
        os.path.join(local_app_data, "Microsoft", "WinGet", "Packages"),
        "C:\\Program Files\\ffmpeg\\bin\\ffmpeg.exe",
        "C:\\ffmpeg\\bin\\ffmpeg.exe",
    ]
    for base in possible_paths:
        if os.path.isfile(base):
            return base
        if os.path.isdir(base):
            for root, _, files in os.walk(base):
                if "ffmpeg.exe" in files:
                    return os.path.join(root, "ffmpeg.exe")
    return None


def find_cjk_font():
    """Find system CJK/TrueType font for crisp Chinese/English text overlay."""
    font_candidates = [
        # Windows fonts
        "C:\\Windows\\Fonts\\msyh.ttc",     # Microsoft YaHei
        "C:\\Windows\\Fonts\\msyh.ttf",
        "C:\\Windows\\Fonts\\simhei.ttf",   # SimHei
        "C:\\Windows\\Fonts\\simsun.ttc",   # SimSun
        "C:\\Windows\\Fonts\\arial.ttf",
        # macOS fonts
        "/System/Library/Fonts/PingFang.ttc",
        "/Library/Fonts/Arial Unicode.ttf",
        # Linux fonts
        "/usr/share/fonts/opentype/noto/NotoSansCJK-Regular.ttc",
        "/usr/share/fonts/truetype/wqy/wqy-zenhei.ttc",
        "/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf",
    ]
    for font_path in font_candidates:
        if os.path.isfile(font_path):
            return font_path
    return None


def draw_text_overlay(img, text, position="bottom"):
    """Draw white text with black outline on PIL Image for meme overlay."""
    if not text:
        return img

    from PIL import ImageDraw, ImageFont

    draw = ImageDraw.Draw(img)
    w, h = img.size

    # Responsive font size (approx 8% of height, min 16px)
    target_font_size = max(16, int(h * 0.08))

    font_path = find_cjk_font()
    font = None
    if font_path:
        try:
            font = ImageFont.truetype(font_path, size=target_font_size)
        except Exception:
            font = None

    if font is None:
        try:
            font = ImageFont.load_default()
        except Exception:
            font = None

    # Calculate text bounding box
    if font and hasattr(draw, "textbbox"):
        bbox = draw.textbbox((0, 0), text, font=font)
        text_w = bbox[2] - bbox[0]
        text_h = bbox[3] - bbox[1]
    elif font and hasattr(font, "getsize"):
        text_w, text_h = font.getsize(text)
    else:
        text_w = len(text) * (target_font_size // 2)
        text_h = target_font_size

    # Calculate X, Y coordinates
    x = max(10, (w - text_w) // 2)
    if position == "top":
        y = int(h * 0.05)
    elif position == "center":
        y = (h - text_h) // 2
    else:  # bottom
        y = h - text_h - int(h * 0.08)

    stroke_w = max(2, target_font_size // 14)

    # Draw text with stroke / border
    try:
        draw.text(
            (x, y),
            text,
            fill="white",
            font=font,
            stroke_width=stroke_w,
            stroke_fill="black"
        )
    except Exception:
        # Fallback for older PIL without stroke parameters
        for dx in range(-stroke_w, stroke_w + 1):
            for dy in range(-stroke_w, stroke_w + 1):
                if dx != 0 or dy != 0:
                    draw.text((x + dx, y + dy), text, fill="black", font=font)
        draw.text((x, y), text, fill="white", font=font)

    return img


def convert_with_ffmpeg_and_pil(ffmpeg_path, video_path, gif_path, fps=12, width=480, text="", position="bottom"):
    """
    Extract frames, apply PIL text overlay, then use ffmpeg palette generation
    to produce ultra-high-quality palettized GIF.
    """
    try:
        import imageio
        from PIL import Image

        reader = imageio.get_reader(video_path)
        meta = reader.get_meta_data()
        orig_fps = meta.get("fps", 24)
        step = max(1, int(round(orig_fps / fps)))

        with tempfile.TemporaryDirectory(prefix="crun_gif_") as temp_dir:
            frame_pattern = os.path.join(temp_dir, "frame_%04d.png")

            frame_idx = 0
            for i, frame in enumerate(reader):
                if i % step == 0:
                    img = Image.fromarray(frame)
                    if width and img.width > width:
                        height = int(img.height * (width / img.width))
                        img = img.resize((width, height), Image.Resampling.LANCZOS)
                    if text:
                        img = draw_text_overlay(img, text, position)
                    
                    frame_file = frame_pattern % frame_idx
                    img.save(frame_file)
                    frame_idx += 1

            if frame_idx == 0:
                return False, "No frames extracted"

            filter_complex = (
                f"split[s0][s1];"
                f"[s0]palettegen=max_colors=256:stats_mode=single[p];"
                f"[s1][p]paletteuse=dither=sierra2_4a"
            )

            cmd = [
                ffmpeg_path,
                "-y",
                "-framerate", str(fps),
                "-i", frame_pattern,
                "-vf", filter_complex,
                "-loop", "0",
                gif_path
            ]

            res = subprocess.run(cmd, stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True)
            if res.returncode == 0 and os.path.exists(gif_path) and os.path.getsize(gif_path) > 0:
                return True, "ffmpeg+PIL"
            return False, res.stderr or "ffmpeg palette conversion failed"
    except Exception as e:
        return False, str(e)


def convert_with_pure_python(video_path, gif_path, fps=12, width=480, text="", position="bottom"):
    """Fallback conversion using Python imageio/cv2/PIL libraries."""
    # Attempt imageio
    try:
        import imageio
        from PIL import Image

        reader = imageio.get_reader(video_path)
        meta = reader.get_meta_data()
        orig_fps = meta.get("fps", 24)
        step = max(1, int(round(orig_fps / fps)))

        frames = []
        for i, frame in enumerate(reader):
            if i % step == 0:
                img = Image.fromarray(frame)
                if width and img.width > width:
                    height = int(img.height * (width / img.width))
                    img = img.resize((width, height), Image.Resampling.LANCZOS)
                if text:
                    img = draw_text_overlay(img, text, position)
                frames.append(img)

        if frames:
            duration_ms = int(1000 / fps)
            frames[0].save(
                gif_path,
                save_all=True,
                append_images=frames[1:],
                optimize=True,
                duration=duration_ms,
                loop=0
            )
            return True, "imageio+PIL"
    except Exception as e:
        imageio_err = str(e)

    # Attempt cv2 + PIL
    try:
        import cv2
        from PIL import Image

        cap = cv2.VideoCapture(video_path)
        orig_fps = cap.get(cv2.CAP_PROP_FPS) or 24
        step = max(1, int(round(orig_fps / fps)))

        frames = []
        count = 0
        while cap.isOpened():
            ret, frame = cap.read()
            if not ret:
                break
            if count % step == 0:
                frame_rgb = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)
                img = Image.fromarray(frame_rgb)
                if width and img.width > width:
                    height = int(img.height * (width / img.width))
                    img = img.resize((width, height), Image.Resampling.LANCZOS)
                if text:
                    img = draw_text_overlay(img, text, position)
                frames.append(img)
            count += 1
        cap.release()

        if frames:
            duration_ms = int(1000 / fps)
            frames[0].save(
                gif_path,
                save_all=True,
                append_images=frames[1:],
                optimize=True,
                duration=duration_ms,
                loop=0
            )
            return True, "cv2+PIL"
    except Exception as e:
        cv2_err = str(e)

    return False, "No valid conversion tool found (ffmpeg/imageio/cv2 missing)"


def main():
    parser = argparse.ArgumentParser(description="Convert MP4 video to GIF meme with optional text overlay.")
    parser.add_argument("video_path", help="Path to input video file")
    parser.add_argument("--output", "-o", help="Path to output GIF file")
    parser.add_argument("--fps", type=int, default=12, help="GIF frame rate (default: 12)")
    parser.add_argument("--width", type=int, default=480, help="GIF scale width in pixels (default: 480)")
    parser.add_argument("--text", "-t", default="", help="Text caption overlay on GIF (bypasses video AI text)")
    parser.add_argument("--text-position", choices=["bottom", "top", "center"], default="bottom", help="Text position (default: bottom)")

    args = parser.parse_args()

    video_path = os.path.abspath(args.video_path)
    if not os.path.isfile(video_path):
        result = {
            "code": 404,
            "status": "failed",
            "error": f"Input video file not found: {video_path}"
        }
        print(json.dumps(result, ensure_ascii=False, indent=2))
        sys.exit(1)

    if args.output:
        gif_path = os.path.abspath(args.output)
    else:
        base, _ = os.path.splitext(video_path)
        gif_path = base + ".gif"

    os.makedirs(os.path.dirname(gif_path), exist_ok=True)

    ffmpeg_bin = find_ffmpeg()
    success = False
    method_used = ""
    err_msg = ""

    if ffmpeg_bin:
        success, res = convert_with_ffmpeg_and_pil(
            ffmpeg_bin, video_path, gif_path, fps=args.fps, width=args.width, text=args.text, position=args.text_position
        )
        if success:
            method_used = res
        else:
            err_msg = f"ffmpeg error: {res}"

    if not success:
        success, res = convert_with_pure_python(
            video_path, gif_path, fps=args.fps, width=args.width, text=args.text, position=args.text_position
        )
        if success:
            method_used = res
        else:
            err_msg = f"{err_msg}; python fallback error: {res}" if err_msg else res

    if success and os.path.isfile(gif_path):
        size_bytes = os.path.getsize(gif_path)
        result = {
            "code": 0,
            "status": "success",
            "input_file": video_path.replace("\\", "/"),
            "output_file": gif_path.replace("\\", "/"),
            "size_bytes": size_bytes,
            "fps": args.fps,
            "width": args.width,
            "text_overlay": args.text,
            "text_position": args.text_position,
            "conversion_method": method_used
        }
        print(json.dumps(result, ensure_ascii=False, indent=2))
        sys.exit(0)
    else:
        result = {
            "code": 500,
            "status": "failed",
            "error": err_msg or "Failed to convert video to GIF"
        }
        print(json.dumps(result, ensure_ascii=False, indent=2))
        sys.exit(1)


if __name__ == "__main__":
    main()
